apiVersion: v1
kind: Pod
metadata:
  name: runner-pod
spec:
  containers:
  - name: runner-container
    image: gitlab/gitlab-runner:alpine3.18-bleeding
    
    ports:
      - containerPort: 8093

    env:
      - name: GITLAB_URL
        value: "http://gitlab-service:80/"
      - name: GITLAB_REGISTRATION_TOKEN
        value: "glrt-CGVy3QbP-NzJ9dhog-pU"
      - name: EXECUTOR
        value: "kubernetes"
      - name: IMAGE
        value: "bitnami/kubectl:1.27.7-debian-11-r0"
      - name: HELPER_IMAGE
        value: "gitlab/gitlab-runner-helper:ubi-fips-x86_64-bleeding"
      - name: CLONE_URL
        value: "http://gitlab-service:80/"

    command: ["/bin/sh","-c"]
    args: ["rm -f /etc/gitlab-runner/config.toml; \
            gitlab-runner register \
            	--non-interactive \
        	--url $GITLAB_URL \
	        --token $GITLAB_REGISTRATION_TOKEN \
         	--executor $EXECUTOR \
        	--kubernetes-image $IMAGE \
        	--kubernetes-helper-image $HELPER_IMAGE \
        	--clone-url $CLONE_URL \
        	&& gitlab-runner run;"]

  restartPolicy: OnFailure

