apiVersion: v1
kind: Pod
metadata:
  name: runner-pod
spec:
  containers:
  - name: runner-container
    image: gitlab/gitlab-runner:alpine3.18-bleeding
    
    ports:
      - containerPort: 8093

    env:
      - name: GITLAB-URL
        value: "http://gitlab-service:80" #Service Gitlab IP
      - name: GITLAB-REGISTRATION-TOKEN
        value: "glrt-yRbKZFs4qmBtnCwrbUJ1"
      - name: EXECUTOR
        value: "shell"

    command: ["gitlab-runner"]
    args: ["register", "--non-interactive", "--url", "$(GITLAB-URL)", "--token", "$(GITLAB-REGISTRATION-TOKEN)", "--executor", "$(EXECUTOR)",\
            "&&", "gitlab-runner", "run"]

    volumeMounts:
      - name: volume-docker
        mountPath: /var/run/docker.sock
      - name: volume-config
        mountPath: /etc/gitlab-runner/

  volumes:
    - name: volume-docker
      hostPath:
        path: /var/run/docker.sock
    - name: volume-config
      hostPath:
        path: /home/shermine237/gitlab-runner-k8s/config
