apiVersion: v1
kind: Pod
metadata:
  name: runner-pod
spec:
  containers:
  - name: runner-container
    image: gitlab/gitlab-runner:alpine3.18-bleeding
    
    ports:
      - containerPort: 8093

    env:
      - name: GITLAB-URL
        value: "http://gitlab-service:80/"
      - name: GITLAB-REGISTRATION-TOKEN
        value: "glrt-yRbKZFs4qmBtnCwrbUJ1"
      - name: EXECUTOR
        value: "docker"
      - name: DOCKER-IMAGE
        value: "alpine:3.18.4"

    command: ["gitlab-runner"]
    args: ["register", "--non-interactive", \
            "--url", "$(GITLAB-URL)", \
            "--token", "$(GITLAB-REGISTRATION-TOKEN)", \
            "--docker-image", "$(DOCKER-IMAGE)", \
            "--executor", "$(EXECUTOR)", \
            "&&", "gitlab-runner", "run"]

    volumeMounts:
      - name: volume-docker
        mountPath: /var/run/docker.sock

  restartPolicy: OnFailure

  volumes:
    - name: volume-docker
      hostPath:
        path: /var/run/docker.sock
