apiVersion: v1
kind: Pod
metadata:
  name: runner-pod
spec:
  containers:
  - name: runner-container
    image: gitlab/gitlab-runner:alpine3.18-bleeding
    
    ports:
      - containerPort: 8093

    env:
      - name: GITLAB_URL
        value: "http://gitlab-service:80/"
      - name: GITLAB_REGISTRATION_TOKEN
        value: "glrt-cBdxZaBg3xcUzCxzuJd7"
      - name: EXECUTOR
        value: "kubernetes"
      - name: IMAGE
        value: "alpine:3.18.4"
      - name: HELPER_IMAGE
        value: "gitlab/gitlab-runner-helper:ubi-fips-x86_64-bleeding"
      - name: NAMESPACE
        value: "dev"
      - name: CLONE_URL
        value: "http://gitlab.local/"
      - name: LISTEN_ADDRESS
        value: "127.0.0.1:80"

    command: ["/bin/sh","-c"]
    args: ["chmod +x /etc/gitlab-runner/entrypoint.sh && /etc/gitlab-runner/entrypoint.sh"]

    volumeMounts:
      - name: config
        mountPath: /etc/gitlab-runner

  restartPolicy: OnFailure

  volumes:
    - name: config
      hostPath:
        path: /home/shermine237/gitlab-runner-k8s/config

