apiVersion: v1
kind: Pod
metadata:
  name: runner-pod
spec:
  containers:
  - name: runner-container
    image: gitlab/gitlab-runner:alpine3.18-bleeding
    
    ports:
      - containerPort: 8093

    env:
      - name: GITLAB-URL
        value: "https://gitlab.com/"
      - name: GITLAB-REGISTRATION-TOKEN
        value: "Token"
      - name: EXECUTOR
        value: "shell"

    command: ["gitlab-runner"]
    args: ["register", "--non-interactive", "--url", "$(GITLAB-URL)", "--token", "$(GITLAB-REGISTRATION-TOKEN)", "--executor", "$(EXECUTOR)"]

    volumeMounts:
      - name: volume-docker
        mountPath: /var/run/docker.sock

  volumes:
    - name: volume-docker
      hostPath:
        path: /var/run/docker.sock
