apiVersion: v1
kind: Pod
metadata:
  name: runner-pod
spec:
  containers:
  - name: runner-container
    image: gitlab/gitlab-runner:alpine3.18-bleeding
    
    ports:
      - containerPort: 8093

    env:
      - name: GITLAB_URL
        value: "http://gitlab-service:80/"
      - name: GITLAB_REGISTRATION_TOKEN
        value: "glrt-yRbKZFs4qmBtnCwrbUJ1"
      - name: EXECUTOR
        value: "kubernetes"

    command: ["/etc/gitlab-runner/entrypoint.sh"]

    volumeMounts:
      - name: config
        mountPath: /etc/gitlab-runner

  restartPolicy: OnFailure

  volumes:
    - name: config
      hostPath:
        path: /home/shermine237/gitlab-runner-k8s/config

